#!/usr/bin/env node
// tools/generate-module.mjs
// Scaffolds a new business module's Controller/Service/Repository/DTO
// skeleton (apps/api) and feature folder (apps/ui), following the verified
// reference pattern in apps/api/src/platform/auth + apps/ui/src/features/auth
// (see CLAUDE.md's "Reference implementation" and FAS_ERP_CODING_STANDARDS.md
// §3). Deliberately mechanical: it does NOT invent a Prisma model, business
// rules, permissions, or auth decisions — every one of those is marked
// `// TODO` in the generated output for a developer (or agent) to fill in.
//
// Usage: node tools/generate-module.mjs <module-name> [--domain <domain>]
//   <module-name>  kebab-case, e.g. "work-orders"
//   --domain       optional business domain folder under modules/ and
//                  features/, e.g. "production" -> modules/production/work-orders
//
// Refuses to overwrite an existing module directory.
import { mkdirSync, existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function fail(message) {
  console.error(`error: ${message}`);
  process.exit(1);
}

function parseArgs(argv) {
  const [name, ...rest] = argv;
  if (!name) {
    fail(
      "missing <module-name> argument. Usage: node tools/generate-module.mjs <module-name> [--domain <domain>]",
    );
  }

  let domain;
  for (let i = 0; i < rest.length; i += 1) {
    if (rest[i] === "--domain") {
      domain = rest[i + 1];
      i += 1;
    }
  }
  return { name, domain };
}

const KEBAB_CASE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

function validateKebabCase(value, label) {
  if (!KEBAB_CASE.test(value)) {
    fail(`${label} "${value}" must be kebab-case (lowercase letters, digits, hyphens — e.g. "work-orders").`);
  }
}

function toPascalCase(kebab) {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function toCamelCase(kebab) {
  const pascal = toPascalCase(kebab);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function toScreamingSnakeCase(kebab) {
  return kebab.toUpperCase().replace(/-/g, "_");
}

// Naive singularization for the common "-s" plural module-name convention
// (work-orders -> WorkOrder) — good enough for the common case; a developer
// renames by hand for irregular plurals (e.g. "inventory").
function toSingularPascalCase(kebab) {
  const pascal = toPascalCase(kebab);
  return pascal.endsWith("s") ? pascal.slice(0, -1) : pascal;
}

function writeFile(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
  console.log(`created: ${path.replace(REPO_ROOT + "/", "")}`);
}

function main() {
  const { name, domain } = parseArgs(process.argv.slice(2));
  validateKebabCase(name, "module-name");
  if (domain) validateKebabCase(domain, "--domain");

  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  const screaming = toScreamingSnakeCase(name);
  const singularPascal = toSingularPascalCase(name);
  const routePath = domain ? `${domain}/${name}` : name;
  const featurePathSegment = domain ? `${domain}/${name}` : name;

  // apps/api/src/modules/[<domain>/]<name>/ — 2 segments under src/ without
  // a domain, 3 with one. Every generated file's relative imports back to
  // src/common, src/shared/prisma, etc. must account for this, so compute
  // the "../" prefix once instead of hardcoding a depth that only holds for
  // the no-domain case.
  const depthUnderSrc = domain ? 3 : 2;
  const up = "../".repeat(depthUnderSrc);

  // apps/ui/src/features/[<domain>/]<name>/hooks/use-<name>.ts's own depth:
  // one level deeper than the api/backend case above (there's a hooks/
  // subfolder), and its "reach a sibling feature" path (features/auth/) is
  // one level shallower than its "reach src/lib" path.
  const uiHooksDepthToSrc = domain ? 4 : 3;
  const uiHooksUpToSrc = "../".repeat(uiHooksDepthToSrc);
  const uiHooksUpToFeatures = "../".repeat(uiHooksDepthToSrc - 1);

  const apiModuleDir = join(REPO_ROOT, "apps/api/src/modules", domain ?? "", name);
  const uiFeatureDir = join(REPO_ROOT, "apps/ui/src/features", domain ?? "", name);

  if (existsSync(apiModuleDir)) fail(`${apiModuleDir} already exists — refusing to overwrite.`);
  if (existsSync(uiFeatureDir)) fail(`${uiFeatureDir} already exists — refusing to overwrite.`);

  const fileHeader = (relPath) =>
    `// ${relPath}\n// Generated by tools/generate-module.mjs.`;

  // ── apps/api ──────────────────────────────────────────────────────────
  writeFile(
    join(apiModuleDir, `${name}.module.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/${name}.module.ts`)} See
// FAS_ERP_CODING_STANDARDS.md §3 for the Controller/Service/Repository
// pattern this follows.
import { Module } from "@nestjs/common";
import { ${pascal}Controller } from "./${name}.controller.js";
import { ${pascal}Repository } from "./${name}.repository.js";
import { ${pascal}Service } from "./${name}.service.js";

@Module({
  controllers: [${pascal}Controller],
  providers: [${pascal}Service, ${pascal}Repository],
  // TODO: export ${pascal}Service only if another module legitimately needs
  // to call into it directly for synchronous coordination (see
  // FAS_ERP_CODING_STANDARDS.md §17's narrow public-service exception) — do
  // not export the repository.
})
export class ${pascal}Module {}
`,
  );

  writeFile(
    join(apiModuleDir, `${name}.controller.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/${name}.controller.ts`)}
// Routing + request/response shape + validation + guards only — no business
// logic (FAS_ERP_CODING_STANDARDS.md §3).
import { Body, Controller, Get, Param, Post, Query } from "@nestjs/common";
import { ApiTags } from "@nestjs/swagger";
import { Paginate } from "${up}common/decorators/paginate.decorator.js";
import type { PaginationDto } from "${up}common/dto/pagination.dto.js";
// TODO: add @RequirePermission("<domain>.${camel}.<action>") once the
// permission string is defined (FAS_ERP_CODING_STANDARDS.md §16/Architecture
// Guide §7) — every route below is currently unguarded.
import { Create${singularPascal}Dto } from "./dto/create-${name}.dto.js";
import { Query${pascal}Dto } from "./dto/query-${name}.dto.js";
import { ${pascal}Service } from "./${name}.service.js";

@ApiTags("${name}")
@Controller("${routePath}")
export class ${pascal}Controller {
  constructor(private readonly ${camel}Service: ${pascal}Service) {}

  @Get()
  findAll(@Paginate() pagination: PaginationDto, @Query() query: Query${pascal}Dto) {
    return this.${camel}Service.findAll(pagination, query);
  }

  @Get(":id")
  findOne(@Param("id") id: string) {
    return this.${camel}Service.findOne(Number(id));
  }

  @Post()
  create(@Body() dto: Create${singularPascal}Dto) {
    return this.${camel}Service.create(dto);
  }
}
`,
  );

  writeFile(
    join(apiModuleDir, `${name}.service.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/${name}.service.ts`)}
// Business rules live here — depends on the repository via constructor
// injection, never on PrismaService directly (FAS_ERP_CODING_STANDARDS.md
// §5's DIP).
import { Injectable } from "@nestjs/common";
import type { PaginationDto } from "${up}common/dto/pagination.dto.js";
import { PaginatedResponseDto } from "${up}common/dto/paginated-response.dto.js";
import type { Create${singularPascal}Dto } from "./dto/create-${name}.dto.js";
import type { Query${pascal}Dto } from "./dto/query-${name}.dto.js";
import { ${pascal}Repository } from "./${name}.repository.js";

@Injectable()
export class ${pascal}Service {
  constructor(private readonly repository: ${pascal}Repository) {}

  async findAll(
    pagination: PaginationDto,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars -- TODO: apply once Query${pascal}Dto has filter fields
    query: Query${pascal}Dto,
  ): Promise<PaginatedResponseDto<unknown>> {
    // TODO: replace with a real repository call once a Prisma model exists
    // for this module (packages/database/prisma/schema.prisma) — this stub
    // throws so it's obvious at runtime that nothing is wired yet, rather
    // than silently returning an empty page that looks like "zero records."
    const items = await this.repository.findMany(pagination);
    return new PaginatedResponseDto(items, pagination.page, pagination.limit, items.length);
  }

  async findOne(id: number): Promise<unknown> {
    // TODO: throw ResourceNotFoundException (common/exceptions) when not found.
    return this.repository.findById(id);
  }

  async create(dto: Create${singularPascal}Dto): Promise<unknown> {
    // TODO: business-rule validation belongs here, before/after the write —
    // not in the controller, not in the repository.
    return this.repository.create(dto);
  }
}
`,
  );

  writeFile(
    join(apiModuleDir, `${name}.service.spec.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/${name}.service.spec.ts`)}
// TODO: replace this placeholder with real tests for this module's business
// rules — FAS_ERP_CODING_STANDARDS.md §7: "every service method with a
// business rule needs a test for the rule, not just the happy path." A
// generated stub with no business logic yet has nothing meaningful to
// assert beyond wiring, so this only proves the module constructs — it is
// NOT a substitute for real coverage once findAll/findOne/create do something.
import { describe, expect, it, vi } from "vitest";
import { ${pascal}Service } from "./${name}.service.js";
import type { ${pascal}Repository } from "./${name}.repository.js";

describe("${pascal}Service", () => {
  it("constructs with an injected repository", () => {
    const repository = {
      findMany: vi.fn(),
      findById: vi.fn(),
      create: vi.fn(),
    } as unknown as ${pascal}Repository;
    const service = new ${pascal}Service(repository);
    expect(service).toBeInstanceOf(${pascal}Service);
  });
});
`,
  );

  writeFile(
    join(apiModuleDir, `${name}.repository.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/${name}.repository.ts`)}
// The ONLY place in this module that may call PrismaService
// (FAS_ERP_CODING_STANDARDS.md §3) — enforced by apps/api/eslint.config.mjs's
// no-restricted-imports rule on *.controller.ts/*.service.ts files, and by
// eslint-plugin-boundaries against other modules importing this file directly.
//
// TODO: this module has no Prisma model yet (packages/database/prisma/schema.prisma).
// Design that model first — following the baseline in
// FAS_ERP_Architecture_Guide.md §6.1 (organization_id, custom_fields,
// created_by/updated_by, created_at/updated_at, deleted_at) and the
// plant-scoping decision rule in §7A — then replace every method body below
// with a real \`this.prisma.<model>.*\` call using \`buildScopedWhere()\`.
import { Injectable } from "@nestjs/common";
import { buildScopedWhere } from "${up}common/utils/org-scope.util.js";
import { PrismaService } from "${up}shared/prisma/prisma.service.js";
import type { PaginationDto } from "${up}common/dto/pagination.dto.js";
import type { Create${singularPascal}Dto } from "./dto/create-${name}.dto.js";

@Injectable()
export class ${pascal}Repository {
  constructor(private readonly prisma: PrismaService) {}

  // TODO: pass { plantScoped: true } to buildScopedWhere() if this table is
  // in the plant-owned bucket (Architecture Guide §7A) — leave it unset for
  // an org-shared catalog. buildScopedWhere() merges the tenant scope in
  // *after* any filter you pass, so a filter can never override it — see
  // that function's own doc comment before changing the merge order.
  findMany(_pagination: PaginationDto): Promise<unknown[]> {
    const where = buildScopedWhere(undefined);
    throw new Error(
      \`${pascal}Repository.findMany: no Prisma model wired yet — see this file's TODO. (where would be \${JSON.stringify(where)})\`,
    );
  }

  findById(_id: number): Promise<unknown | null> {
    const where = buildScopedWhere(undefined);
    throw new Error(
      \`${pascal}Repository.findById: no Prisma model wired yet — see this file's TODO. (where would be \${JSON.stringify(where)})\`,
    );
  }

  create(_dto: Create${singularPascal}Dto): Promise<unknown> {
    const scope = buildScopedWhere(undefined);
    throw new Error(
      \`${pascal}Repository.create: no Prisma model wired yet — see this file's TODO. (scope would be \${JSON.stringify(scope)})\`,
    );
  }
}
`,
  );

  writeFile(
    join(apiModuleDir, "dto", `create-${name}.dto.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/dto/create-${name}.dto.ts`)}
// TODO: add real fields with class-validator decorators once this module's
// shape is designed — an empty DTO accepts an empty body today
// (ValidationPipe's forbidNonWhitelisted will reject any field you send
// until you add it here).
export class Create${singularPascal}Dto {}
`,
  );

  writeFile(
    join(apiModuleDir, "dto", `update-${name}.dto.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/dto/update-${name}.dto.ts`)}
// TODO: usually PartialType(Create${singularPascal}Dto) from @nestjs/swagger
// once Create${singularPascal}Dto has fields — kept as its own operation-specific
// DTO per FAS_ERP_CODING_STANDARDS.md §5 (Interface Segregation), never
// merged with the create DTO.
export class Update${singularPascal}Dto {}
`,
  );

  writeFile(
    join(apiModuleDir, "dto", `query-${name}.dto.ts`),
    `${fileHeader(`apps/api/src/modules/${featurePathSegment}/dto/query-${name}.dto.ts`)}
// TODO: add filter fields (status, date range, search text, ...) with
// class-validator decorators — pagination itself is handled separately by
// @Paginate() (FAS_ERP_CODING_STANDARDS.md §15), don't duplicate page/limit here.
export class Query${pascal}Dto {}
`,
  );

  // ── apps/ui ───────────────────────────────────────────────────────────
  writeFile(
    join(uiFeatureDir, "api.ts"),
    `// apps/ui/src/features/${featurePathSegment}/api.ts
// Generated by tools/generate-module.mjs. TODO: replace the endpoint path
// below once the backend route is real, and give the response a real type
// from @fas-erp/api-types (or a locally-colocated type until that package
// generates it — FAS_ERP_CODING_STANDARDS.md §11).
export const ${screaming}_ENDPOINTS = {
  LIST: "/${routePath}",
} as const;
`,
  );

  writeFile(
    join(uiFeatureDir, "hooks", `use-${name}.ts`),
    `// apps/ui/src/features/${featurePathSegment}/hooks/use-${name}.ts
// Generated by tools/generate-module.mjs — reference pattern:
// apps/ui/src/features/auth/hooks/use-permission-check.ts and
// FAS_ERP_CODING_STANDARDS.md §19A (org/plant-aware query keys).
// TODO: replace the placeholder response type and enable this once the
// backend route in ${name}.controller.ts actually returns data.
"use client";

import { useQuery, type UseQueryResult } from "@tanstack/react-query";
import { apiClient } from "${uiHooksUpToSrc}lib/api-client.js";
import { useAuth } from "${uiHooksUpToFeatures}auth/auth-context.js";
import { ${screaming}_ENDPOINTS } from "../api.js";

interface ${pascal}ListResponse {
  // TODO: real shape.
  [key: string]: unknown;
}

export function use${pascal}(): UseQueryResult<${pascal}ListResponse, unknown> {
  const { user, status } = useAuth();

  return useQuery({
    queryKey: ["${name}", "list", user?.organizationId, user?.activePlantId],
    queryFn: () => apiClient.request<${pascal}ListResponse>(${screaming}_ENDPOINTS.LIST),
    enabled: status === "authenticated",
  });
}
`,
  );

  writeFile(
    join(uiFeatureDir, "components", ".gitkeep"),
    `Placeholder — this module's domain-aware components (e.g. a
"${pascal}Table", "${singularPascal}Form") go here once the UI is built.
See FAS_ERP_CODING_STANDARDS.md §4 for the primitive-vs-widget split:
generic/dumb pieces come from @fas-erp/ui-kit, this folder is only for
components that know about "${name}" specifically.
`,
  );

  console.log(`
Generated "${name}"${domain ? ` under domain "${domain}"` : ""}. Still required before this is real:
  1. Design the Prisma model(s) this module needs (packages/database/prisma/schema.prisma)
     and run a migration — the generated repository throws until that exists.
  2. Register ${pascal}Module in apps/api/src/app.module.ts.
  3. Define and seed the permission string(s) this module needs, and add
     @RequirePermission() to the controller's routes.
  4. Fill in the DTOs' fields.
  5. Replace the placeholder response type in use-${name}.ts once the route returns real data.
  6. Write real tests for this module's business rules (not just the generated wiring stub).
This scaffold is NOT production-ready as generated — see the TODOs in each file.
`);
}

main();
